spring:
  application:
    name: moghilan-cloud-eureka-client-discovery-service
server:
  port: 8081
eureka:
  client:
    service-url:
    #  defaultZone: http://peer-0-server:9000/eureka, http://peer-1-server.com:9001/eureka, http://peer-2-server.com:9002/eureka, http://peer-3-server.com:8761/eureka
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      preferIpAddress: true
      status-page-url-path: https://${eureka.instance.hostName}/info
      health-check-url: https://${eureka.instance.hostName}/health
      home-page-url: https://${eureka.instance.hostName}/
    healthcheck:
      enabled: true
